### ISSUE TITLE
Adapter crashes

### ISSUE THREAD

**Issue by SVallant** [minukodu/ioBroker.minuaru#16]
2022-06-13 10:28:19.439  - [34mdebug[39m: minuaru.0 (748709) state at reset debounce timer: {"val":false,"ack":true,"ts":1655108784501,"q":0,"from":"system.adapter.hm-rpc.1","user":"system.user.admin","lc":1643700174842}
2022-06-13 10:28:19.443  - [31merror[39m: minuaru.0 (748709) uncaught exception: Cannot read property 'valueAtAlarm' of undefined
2022-06-13 10:28:19.445  - [31merror[39m: minuaru.0 (748709) TypeError: Cannot read property 'valueAtAlarm' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.minuaru/main.js:408:87)
    at processImmediate (internal/timers.js:466:21)

**Comment by SVallant** [comment]
needs more info plz install v0.9.8 and post log

**Comment by SVallant** [comment]
solved with v1.0.0
